# Packages
php_xdebug_default_enable: 1
php_xdebug_idekey: PHPSTORM
php_xdebug_remote_autostart: 1

# Extras
installed_extras:
  - adminer
  - mailhog
  - pimpmylog
  - drush
  - drupalconsole
  - xdebug
